### ISSUE TITLE
Repeat strategy limitation

### ISSUE THREAD

**Issue by AI-Joe** [litmuschaos/chaos-scheduler#8]
Problem
=======

The current definitions of start and end time boxes the repeat strategy in. Meaning that you could not repeat indefinitely or even for multiple days between certain hours. The use case is to execute experiments on a schedule within business hours/days for an extended or indefinite duration of time.

Current
=======
```
repeat:
      startTime: "2020-08-03T13:00:00Z"
      endTime: "2020-08-03T21:00:00Z"
      minChaosInterval: "30m"
      instanceCount: "1"
      includedDays: "Mon,Tue,Wed,Thu,Fri"
```

This will start at 1pm and end at 8:30pm UTC on the day defined. I'm not really sure where the included days come in to play here. The cron expression created seems like the actual day of the repeat times would not affect the creation of the engines. However, when the engines are actually created it will end the schedule once it is after the user specified end time.

```
repeat:
      startTime: "2020-08-03T13:00:00Z"
      endTime: "2021-08-03T21:00:00Z"
      minChaosInterval: "30m"
      instanceCount: "1"
      includedDays: "Mon,Tue,Wed,Thu,Fri"
```

This example, without temporarily halting the schedule, will execute every 30 minutes from the start to the end time excluding weekends.

Future
======

```
repeat:
      startTime: "2020-08-03T13:00:00Z"
      endTime: "2021-08-03T21:00:00Z"
      minChaosInterval: "30m"
      instanceCount: "1"
      includedDays: "Mon,Tue,Wed,Thu,Fri"
      indefinite: true (default false)
```

By adding this field the user can opt out of the after end time check, creating an indefinite repeat schedule. Then in the creation of the cron expression you could have something like return fmt.Sprintf("*/%d %d-%d * * %s", interval, startHour, endHour, includedDays), time.Minute * time.Duration(interval), nil

**Comment by ksatchit** [comment]
Thank you @AI-Joe !! This makes sense, the schema definitely needs more refining. cc: @Sanjay1611

**Comment by Sanjay1611** [comment]
Thank you @AI-Joe !! Its a good catch, We definitely want to improve the schema over time

**Comment by Sanjay1611** [comment]
An alternate approach can be -
We can allow `endTime` and `startTime` to be nil. Then whenever the `startTime` is nil we will take it as `creationTime` of the CR and whenever the `endTime` is nil we will take the schedule to repeated infinitely. For e.g.
```
repeat:
      startTime: "2020-08-03T13:00:00Z"
      minChaosInterval: "30m"
      instanceCount: "1"
      includedDays: "Mon,Tue,Wed,Thu,Fri"
```
This example is not having any `endTime`. So the schedule will be repeated from the `startTime` infinitely

```
repeat:
      endTime: "2021-08-03T21:00:00Z"
      minChaosInterval: "30m"
      instanceCount: "1"
      includedDays: "Mon,Tue,Wed,Thu,Fri"
```
This example is not having any `startTime`. So the schedule will be repeated between `creationTime` and `endTime`

```
repeat:
      minChaosInterval: "30m"
      instanceCount: "1"
      includedDays: "Mon,Tue,Wed,Thu,Fri"
```
This example is missing both the timestamps. So the schedule will be repeated from `creationTime` infinitely

**Comment by Sanjay1611** [comment]
What are your views on this @AI-Joe

**Comment by AI-Joe** [comment]
@Sanjay1611 I think that allowing endTime/startTime to be nil is a better approach to allowing infinite that I proposed. 

I only briefly mentioned this in the problem, but allowing an infinite repeat feels incomplete to me without run hour restrictions. 
```
repeat:
      minChaosInterval: "30m"
      instanceCount: "1"
      includedDays: "Mon,Tue,Wed,Thu,Fri"
      includedHours: "13-21" #should be able to be any cron accepted time annotation in UTC
```

This example is an infinite repeat that doesn't run after business hours. By not including the includedHours field the user is selecting to run every hour.

**Comment by Sanjay1611** [comment]
@AI-Joe I think `includedHours` field would be really helpful. We should have it in our schema. 
But `minChaosInterval` will have to support the hours too. So that we can have minimum number of hours between 2 chaos executions.

**Comment by calvinbui** [comment]
+1 to `includedHours` when we keep it within business hours

+1 to [empty startTimes and endTimes](https://github.com/litmuschaos/chaos-scheduler/issues/8#issuecomment-668861766)

**Comment by Sanjay1611** [comment]
Will be changing `repeat` structure to 
```
repeat:
  timeRange:
    startTime:
    endTime:
  properties:
    minChaosINterval:
    instanceCount:
    random:
  workHours:
    includedHours:
  workDays:
    includedDays:
```

`timeRange`, `workHours` and `workDays` will be optional fields

cc @AI-Joe @calvinbui
